### ISSUE TITLE
Target path may accept patterns

### ISSUE THREAD

**Issue by ogizanagi** [Elao/VoucherAuthenticationBundle#2]
It would be great if the target path of a voucher can be set when generating the url, in order to access an identified resource:

`http://example.com/voucher?token=FVJHRC45TEKUYYUY543TUGYH&target_path=http://example.com/resource/RESOURCE_ID

```yml
security:
    firewalls:
        main:
            voucher:
                target_paths:
                    tmp_access: '^/resource/.*'
```

(It can make use of the `RequestMatcher` for configuring and matching the path)

The issue is that it should not always allow to access all resources under `http://example.com/resource`. Thus we should allow to store the exactly allowed target_paths in the generated token.
